name: Deploy to VM

on:
  push:
    branches:
      - main  # Atau nama branch yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: "latest" # atau tulis versi spesifik

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Run app on VM
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ti3a@70.153.16.116 '
          cd ~/app &&
          git pull origin main && 
          bun install && 
          bun build && 
          bun start
        '