name: Deploy to VM

on:
  push:
    branches:
      - main  # Atau nama branch yang sesuai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: "latest" # atau tulis versi spesifik

    # Install dependencies and build the app on GitHub Actions
    - name: Install dependencies and build app
      run: |
        /home/runner/.bun/bin/bun install
        /home/runner/.bun/bin/bun run build
    # Copy the build result to the VM
    - name: Copy build files to VM
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r build/* ti3a@70.153.16.116:/home/ti3a/agentravel-backend/
    
    - name: Kill existing app process on VM
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ti3a@70.153.16.116 '
          echo "Stopping any existing bun processes..."
          exec pkill -f "[b]un ./backend.js" || echo "No process to kill"
        '

    # Run app on VM (only after build is copied)
    - name: Run app on VM
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ti3a@70.153.16.116 '
          cd ~/agentravel-backend &&
          nohup ~/.bun/bin/bun ./backend.js > bun.log 2>&1 &
        ' >/dev/null 2>&1 & sleep 10